### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by mawzub** [pkp/vagrant#11]
I'm using vagrant box to set up a local environment for magento cloud commerce.

So far I've gotten as far as attempting to go through GitHub and that's where I see the "Permission denied (publickey)"

I'm not too sure what's stopping me. I've read troubleshooting guide here https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey

Nothing seems to be working. 

Any suggestion on what I should be doing instead?

**Comment by asmecher** [comment]
@mawzub, which of our apps are you working with (e.g. OJS or OMP)? Can you post the output of your `vagrant up` command?

**Comment by mawzub** [comment]
Hi @asmecher got past this point. Turns out I was getting denied due to access restrictions.

Thanks for reaching out though.
