### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by samueloph** [pkp/vagrant#3]
I've just tested this on two different OSes (Arch Linux and Debian Testing), and altough the vagrant up process finishes sucessfully, I'm not able to login at http://localhost:8000/ojs/.
user: admin
passw: admin

Could this be some issue on my side? (I highly believe it's not because vagrant, my system shouldn't alter the funcionality).

The generated admin password's hash is:
$2y$10$HfhqAbvj9YqbcaKkXYxlPuFnowhItH8AcixTXD3wWrBqplHotwsa6

I don't know how the salting works on OJS, so maybe someone could check if the hash comes from an admin password.

Steps to reproduce:
*vagrant up
*login at http://localhost:8000/ojs/
*fail

**Comment by asmecher** [comment]
Hmm, I just tried this and it worked for me. My hash is different: `$2y$10$N7uniXzWip1L5Vo3AAsYZucf3Y/yUfgJ/8p6RGhOXqh.QPjgRHEva`

**Comment by samueloph** [comment]
Oh sorry, I forgot to mention that I'm using the 2_4_7 branch.

**Comment by asmecher** [comment]
For ojs-stable-2_4_7, the credentials are different; see the README.md for that branch.

**Comment by samueloph** [comment]
Oh, I did not realize that branch had a different README.md.

Thanks Alec!

**Comment by asmecher** [comment]
No problem -- just because OJS 2.4.x has different password length requirements, so the same password couldn't be used.
