### ISSUE TITLE
The installed PHP version is 5.5

### ISSUE THREAD

**Issue by ajnyga** [pkp/vagrant#6]
It seems that the installed PHP version is 5.5 while 5.6 is the minimum requirement.

**Comment by asmecher** [comment]
I'm taking a look at this now -- shouldn't take long. I suspect just switching out the `php5` packages in the scripts for `php7` instead, and choosing `mysqli` instead of `mysql` in the OJS install `POST` request, will be enough.

**Comment by asmecher** [comment]
@ajnyga, thanks for reporting -- the patch I've just committed should resolve it by updating the base Vagrant image to something way more modern. The old Trusty-based configuration couldn't run anything newer than PHP5.5 without a lot of (unnecessary) back-configuration work. I'm still testing the new one, but it looks like it's working.
