### ISSUE TITLE
SSH gives vagrant@localhost: Permission denied (publickey).

### ISSUE THREAD

**Issue by ajnyga** [pkp/vagrant#7]
Hi,

Running with OS X High Sierra doing vagrant up works fine, but doing `ssh -p 2222 vagrant@localhost` give an error: `vagrant@localhost: Permission denied (publickey).`

Happy to hear if someone who has used vagrant more knows what the issue is.

**Comment by axfelix** [comment]
It doesn't look like the Vagrantfile is actually exposing port 2222...

**Comment by asmecher** [comment]
Have you tried running `vagrant ssh` rather than the manual SSH command line?

**Comment by ajnyga** [comment]
yes, meant to say that `vagrant ssh` it works, but I was hoping to establish a sftp connection and there I run to the same problem and can not use vagrant ssh of course.

**Comment by axfelix** [comment]
I think we'd need to actually expose 2222 in that case

**Comment by ajnyga** [comment]
I do not think it is a problem with the port, because I can get in using `ssh -i .vagrant/machines/default/virtualbox/private_key -p 2222 vagrant@127.0.0.1`. So it is something todo with the ssh keys, not sure what.

**Comment by ajnyga** [comment]
Ok, so I was able to give a private key for the ftp program as well and was able to get it working. But I do think that this should not be required, just do not know any better way of fixing it.

edit: maybe add config.ssh.private_key_path

**Comment by jmpreston** [comment]
I'm able to get in to my vagrant box with `ssh -i ~/.ssh/id_ecdsa -p 2222 vagrant@127.0.0.1` as suggested above by ajnyga but not `vagrant ssh`.  Interesting.  I would prefer to go back to `vagrant ssh` instead of this hack.  I'm using:  
`mybox.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_ecdsa"]`

**Comment by asmecher** [comment]
@svstartuplab, I think this is more of a general Vagrant question than an OJS question, the vagrant configuration file in this repo is pretty short and sweet and doesn't make particular reference to the SSH setup. I suspect if you were to boot the `ubuntu/xenial64` box our vagrant image is based on, you'd have the same problem.
