### ISSUE TITLE
Call to undefined function mb_split throws fatal error

### ISSUE THREAD

**Issue by jhallida** [pkp/vagrant#8]
It looks like a new issue has crept in within the last week or so. Creating the VM box itself works fine but OJS will not start up properly. I found this is the error logs:

PHP Fatal error:  Uncaught Error: Call to undefined function mb_split() in /var/www/html/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/shared.mb_str_replace.php:47

Running 
`sudo apt-get install php-mbstring` 
on the VM seems to fix the problem and when rebooting OJS will start as normal

**Comment by asmecher** [comment]
Thanks! This appears to be related to an Ubuntu VM update. I've confirmed both the problem and the fix, and added the `php-mbstring` package to the install scripts.
